spring.application.name=discografia
spring.data.mongodb.uri=mongodb+srv://eva2_spring:mrfttHTPlY2gTeeK@cluster-spring.xvoehhx.mongodb.net/?retryWrites=true&w=majority&appName=cluster-spring
spring.data.mongodb.database=discografica-db
